### PR TITLE
chore: fix linter

### PR DESCRIPTION
**Pull request by tbruyelle**
- fix govgen import path in gci tool configuration in  the `.golangci.yml` file
- fix import order in respect of that configuration (`make format` can do that automatically)
- fix usage of `//nolint: unparam`

Not sure if we should target `feat/custom-gov-module` or `main` branch, give me your though!

### CODE REVIEW

**Comment by giunatale** [comment]
@tbruyelle let's target main, I think it makes sense especially as we are approaching merging also the gov modifications.

**Review by giunatale — APPROVED** [review]
Either way, main or feature branch, we soon enough will upstream these changes so it doesn't really makes that much diff.

I am thinking main, but tbh it's really the same.

**Comment by tbruyelle** [comment]
Thinking about it, even if we target `main', we still need a linter PR for the feature branch, for the `gov' module we've added. So let's merge it there.

**Comment by giunatale** [comment]
> Thinking about it, even if we target `main', we still need a linter PR for the feature branch, for the `gov' module we've added. So let's merge it there.

makes a lot of sense! 
LGTM

**Pull request merged**
